version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
        environment:
          POSTHOG_HOST: "https://us.posthog.com"
          DEBUG: "False"
          ALLOWED_HOSTS: "localhost,127.0.0.1"
          VITE_API_URL: "http://localhost:8000/api"
          VITE_POSTHOG_HOST: "https://us.posthog.com"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker images
          command: docker compose build

  test:
    docker:
      - image: cimg/base:stable
        environment:
          POSTHOG_HOST: "https://us.posthog.com"
          DEBUG: "False"
          ALLOWED_HOSTS: "localhost,127.0.0.1"
          VITE_API_URL: "http://localhost:8000/api"
          VITE_POSTHOG_HOST: "https://us.posthog.com"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker images
          command: docker compose build
      - run:
          name: Start services
          command: docker compose up -d
      - run:
          name: Wait for backend to be ready
          command: |
            docker compose exec backend bash -c 'until nc -z localhost 8000; do sleep 1; done'
      - run:
          name: Run backend tests
          command: docker compose exec backend python manage.py test --keepdb
      - run:
          name: Run frontend tests
          command: docker compose exec frontend npm run test
      - run:
          name: Stop services
          command: docker compose down

  lint:
    docker:
      - image: cimg/base:stable
        environment:
          POSTHOG_HOST: "https://us.posthog.com"
          DEBUG: "False"
          ALLOWED_HOSTS: "localhost,127.0.0.1"
          VITE_API_URL: "http://localhost:8000/api"
          VITE_POSTHOG_HOST: "https://us.posthog.com"
    steps:
      - checkout
      - run:
          name: Lint frontend
          command: cd frontend && npm run lint
      - run:
          name: Lint backend
          command: cd backend && source venv/bin/activate && npm run backend:lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint
      - test:
          requires:
            - build 