# Generated by Django 4.2.23 on 2025-07-20 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pageviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_views", models.IntegerField(default=0)),
                ("time_spent_home", models.IntegerField(default=0)),
                ("time_spent_about", models.IntegerField(default=0)),
                ("time_spent_skills", models.IntegerField(default=0)),
                ("time_spent_projects", models.IntegerField(default=0)),
                ("time_spent_resume", models.IntegerField(default=0)),
                ("time_spent_contact", models.IntegerField(default=0)),
                (
                    "most_viewed_section",
                    models.CharField(default="home", max_length=20),
                ),
                ("average_session_duration", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page Analytics",
                "verbose_name_plural": "Page Analytics",
            },
        ),
        migrations.DeleteModel(
            name="PageView",
        ),
    ]
