# Generated by Django 4.2.7 on 2025-07-21 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pageviews", "0002_pageanalytics_delete_pageview"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pageanalytics",
            table="page_analytics",
        ),
    ]
